<?php
/**
 * This file is part of Mbiz_AdvancedReports for Magento.
 *
 * @license MIT
 * @author Jacques Bodin-Hullin <j.bodinhullin@monsieurbiz.com> <@jacquesbh>
 * @category Mbiz
 * @package Mbiz_AdvancedReports
 * @copyright Copyright (c) 2015 Monsieur Biz (http://monsieurbiz.com)
 */
/* @var $this Mage_Page_Block_Html_Head */
?>
<?php if ($_req = Mage::app()->getRequest()->getParam('request')): ?>
<script type="text/javascript">
// <![CDATA[
ADVANCED_REPORTS_REQUEST = '<?php echo $this->jsQuoteEscape($this->escapeHtml($_req)); ?>';
// ]]>
</script>
<?php endif; ?>
<?php echo $this->getCssJsHtml() ?>