<?php
/**
 * This file is part of Mbiz_AdvancedReports for Magento.
 *
 * @license GPL-3.0+
 * @author Jacques Bodin-Hullin <j.bodinhullin@monsieurbiz.com> <@jacquesbh>
 * @category Mbiz
 * @package Mbiz_AdvancedReports
 * @copyright Copyright (c) 2015 Monsieur Biz (http://monsieurbiz.com)
 */
/* @var $this Mbiz_AdvancedReports_Block_Adminhtml_Board */
?>

<div class="content-header">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td style="width:100%;">
                    <h3 class="icon-head head-edit-form"><?php echo $this->getBoardLabel(); ?></h3>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<?php echo $this->getChildHtml('request-selector'); ?>

<div id="request-zone"></div>

<script type="text/javascript">
    Board.init({
        request_zone: "request-zone",
        request_form_id: "request_fields_form",
        request_form_validate_url: "<?php echo $this->getUrl('*/*/validate', array('board' => $this->getBoardId())); ?>",
        request_selector_id: "request_id",
        export_flag_field_id: "export_flag",
        request_form_url: "<?php echo $this->getUrl('*/*/requestForm', array('board' => $this->getBoardId())); ?>"
    });
</script>
